export type AuthUser = { id: string; email: string; displayName?: string | null };
export type AuthWorkspace = { id: string; name: string; type: string; role: string };
export type AuthResponse = { accessToken: string; user: AuthUser; workspaces: AuthWorkspace[] };
export type PagedResult<T> = { items: T[]; page: number; pageSize: number; totalCount: number };
export type Workspace = { id: string; name: string; description?: string | null; ownerId: string };
export type Project = { id: string; workspaceId: string; name: string; description?: string | null };
export type Board = { id: string; projectId: string; name: string };
export type Column = { id: string; boardId: string; name: string; position: number };
export type TaskItem = {
  id: string;
  projectId: string;
  boardColumnId: string;
  parentTaskItemId?: string | null;
  title: string;
  description?: string | null;
  position: number;
  dueDateUtc?: string | null;
  assigneeId?: string | null;
};
export type WorkspaceCreateRequest = { name: string; description?: string; type?: 'Personal' | 'Team' };
export type ProjectCreateRequest = { workspaceId: string; name: string; description?: string; color?: string; icon?: string };
export type BoardCreateRequest = { projectId: string; name: string };
export type ColumnCreateRequest = { boardId: string; name: string; position: number; order?: number };
export type TaskItemCreateRequest = {
  projectId: string;
  boardColumnId: string;
  parentTaskItemId?: string | null;
  title: string;
  description?: string;
  status?: string;
  priority?: string;
  deadlineUtc?: string | null;
  dueDateUtc?: string | null;
  order?: number;
  position: number;
  assigneeId?: string | null;
};
export type ProjectOverview = {
  id: string;
  workspaceId: string;
  name: string;
  description?: string | null;
  boards: Array<{ id: string; name: string; order: number; columnsCount: number; tasksCount: number }>;
  notes: Array<{ id: string; title: string; contentMarkdown: string; createdAtUtc: string }>;
  stats: { totalTasks: number; completedTasks: number; overdueTasks: number };
};
export type KanbanBoard = { id: string; projectId: string; name: string; columns: KanbanColumn[] };
export type KanbanColumn = { id: string; name: string; order: number; tasks: KanbanTask[] };
export type KanbanTask = {
  id: string;
  projectId: string;
  boardColumnId: string;
  parentTaskItemId?: string | null;
  title: string;
  description?: string | null;
  status: string;
  priority: string;
  deadlineUtc?: string | null;
  order: number;
  labels: Array<{ id: string; name: string; color: string }>;
  checklist: { total: number; completed: number };
  subtasks: { total: number; completed: number };
  commentsCount: number;
  attachmentsCount: number;
};
export type TaskDetails = KanbanTask & {
  boardColumnId: string;
  parentTaskItemId?: string | null;
  description?: string | null;
  checklistItems: Array<{ id: string; text: string; isCompleted: boolean; order: number }>;
  comments: Array<{ id: string; authorId: string; body: string; createdAtUtc: string }>;
  attachments: Array<{ id: string; fileName: string; contentType: string; url: string; sizeBytes: number }>;
  subtasks: KanbanTask[];
};
